local_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  obstacle_layer:
   observation_sources: laser_scan_sensor
   laser_scan_sensor: 
     sensor_frame: base_scan
     topic: /scan
     data_type: LaserScan
     marking: true
     clearing: true
  
