global_frame: "map"
base_frame: "base_link"
goal_topic_name: "move_base_simple/goal"
odom_topic_name: "odom"
loop_rate: 20
vel_stop_theshhold: 0
omega_stop_theshhold: 0
robot_width: 0.5
robot_length: 0.8

dwa:
 loop_rate: 20
 max_vel: 0.8
 min_vel: 0
 max_acc: 1.0
 max_w: 1
 min_w: -1
 max_dw: 3
 dt: 0.1
 v_resolution: 0.02
 w_resolution: 0.02
 predict_time: 3.0
 goal_gain: 0.05
 speed_gain: 0.5
 ob_gain: 0.01
 robot_radius: 0.25
 range: 0.1

pp:
 loop_rate: 20
 max_vel: 1.0
 min_vel: 0
 set_vel: 0.7
 max_acc: 0.5
 stop_dec: 1.0
 max_w: 1.0
 min_w: -1.0
 max_dw: 6.981
 dt: 0.05
 wp_range: 2.5
 goal_range: 0.2
 stop_vel: 0.3
 look_dist: 1.0
 stop_dist: 1.0
 predict_time: 3.0

 

line_planner:
 loop_rate: 20
 max_vel: 0.3
 max_vel_in_curve: 0.15
 min_vel: 0
 max_w: 0.785398
 min_w: -0.785398
 vel_acc: 0.3
 gain_omega: 40
 gain_phi: 40
 gain_eta: 20
 max_eta: 1.5
