global_frame: "map"
base_frame: "base_link"
goal_topic_name: "move_base_simple/goal"
loop_rate: 20
vel_stop_theshhold: 0
omega_stop_theshhold: 0
robot_width: 0.5
robot_length: 0.8
dwa:
 max_vel: 0.3
 min_vel: 0
 max_acc: 0.2
 max_w: 0.6981
 min_w: -0.6981
 max_dw: 0.6981
 dt: 0.1
 v_resolution: 0.01
 w_resolution: 0.01
 predict_time: 3.0
 goal_gain: 1.0
 speed_gain: 1.0
 ob_gain: 0.2
 robot_radius: 0.3
 

line_planner:
 loop_rate: 20
 max_vel: 0.5
 min_vel: 0
 max_w: 0.6981
 min_w: -0.6981
 vel_acc: 0.2
 gain_omega: 0.5
 gain_phi: 0.2
 gain_eta: 0.1
 eta_max: 2.0
