global_frame: "map"
base_frame: "base_link"
goal_topic_name: "move_base_simple/goal"
odom_topic_name: "odom"
loop_rate: 20
vel_stop_theshhold: 0
omega_stop_theshhold: 0
robot_width: 0.5
robot_length: 0.8
dwa:
 max_vel: 0.5
 min_vel: 0
 max_w: 0.6981
 min_w: -0.6981
 max_dw: 0.6981
 dt: 0.1
 v_resolution: 0.01
 w_resolution: 0.01
 predict_time: 3.0
 to_goal_cost: 1.0
 speed_cost_gain: 1.0
 robot_radius: 0.3
 max_acc: 0.2

line_planner:
 loop_rate: 100
 max_vel: 0.3
 max_vel_in_curve: 0.15
 min_vel: 0
 max_w: 0.785398
 min_w: -0.785398
 vel_acc: 0.3
 gain_omega: 40
 gain_phi: 40
 gain_eta: 20
 max_eta: 1.5
